save_dir: 'save_model'
save_tag: '230217_argo'
device: 'cuda:0'
test_include: False
num_epochs: 50
modality: 'bev'
save_model: True
save_interval: 10
distributed: 1
fpv_type: 'self'

DATA:
  obs_len: 20
  pred_len: 30
  batch_size: 64
  subset: False
  split: True

DATALOADER:
  data_dir: '../argoverse-data/processed'
  calib_path: '../argoverse-data/vehicle_calibration_info.json'
  num_worker: 0
  shuffle: True

MODEL:
  hidden_size: 128
  share_weight: True
  num_samples: 1
  tgt_random: False

SOLVER:
  lr: 0.001
  bev_weight: 1.0
  fpv_weight: 1.0
  step_size: 50
  scheduler_lr_type: 'm'
  grad_clip: 0.01
  patience: 20
  milestones: (50, 100)

EVAL:
  optimization: True
  MRminFDE: 0
  cnt_sample: 9
  opti_time: 0.1
  core_num: 16

